name: Latest blog post workflow

on:
  schedule:
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme-with-blog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/jglg"
          max_post_count: 3
          date_format: "d mmm yyyy, HH:MM"
          template: "<table width=\"100%\"><tr><td width=\"15%\" align=\"center\"><a href=\"$url\"><img width=\"80\" height=\"80\" src=\"https://wsrv.nl/?url=github.com/JglgTv.png&w=80&h=80&mask=circle&output=png\" alt=\"Avatar\"></a></td><td width=\"85%\"><h3><a href=\"$url\" style=\"text-decoration: none;\">$title</a></h3><p style=\"color: #888;\">$date</p></td></tr></table><br/>"
